version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "01:30"
  open-pull-requests-limit: 10
  target-branch: dev
  assignees:
      - "sadrasabouri"
      - "sepandhaghighi"
  ignore:
  - dependency-name: numpy
    versions:
    - 1.19.5
    - 1.20.0
