name: Bug Report
description: File a bug report
title: "[Bug]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Provide a clear and concise description of what the bug is.
      placeholder: Tell us a description of the bug.
    validations:
      required: true
  - type: textarea
    id: step-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Provide details of how to reproduce the bug.
      placeholder: ex. 1. Go to '...'
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What you expected to happen?
      placeholder: ex. I expected '...' to happen
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: What actually happened?
      placeholder: ex. Instead '...' happened
    validations:
      required: true
  - type: dropdown
    id: operating-system
    attributes:
      label: Operating system
      description: What operating system are you using?
      options:
        - Windows
        - macOS
        - Linux
      default: 0
    validations:
      required: true
  - type: dropdown
    id: python-version
    attributes:
      label: Python version
      description: Which version of Python are you using?
      options:
        - 3.12
        - 3.11
        - 3.10
        - 3.9
        - 3.8
        - 3.7
        - 3.6
        - 3.5
      default: 1
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of PyCM are you using?
      options:
        - 4.0
        - 3.9
        - 3.8
        - 3.7
        - 3.6
        - 3.5
        - 3.4
        - 3.3
        - 3.2
        - 3.1
        - 3.0
        - 2.9
        - 2.8
        - 2.7
        - 2.6
        - 2.5
        - 2.4
        - 2.3
        - 2.2
        - 2.1
        - 2.0
        - 1.9
        - 1.8
        - 1.7
        - 1.6
        - 1.5
        - 1.4
        - 1.3
        - 1.2
        - 1.1
        - 1.0
        - 0.9.5
        - 0.9
        - 0.8.6
        - 0.8.5
        - 0.8.1
        - 0.7
        - 0.6
        - 0.5
        - 0.4
        - 0.3
        - 0.2
        - 0.1
      default: 0
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
