name: Feature Request
description: Suggest a feature for this project
title: "[Feature]: "
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature you want to add
    validations:
      required: true
  - type: textarea
    id: possible-solution
    attributes:
      label: Describe your proposed solution
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered, if relevant
    validations:
      required: false
  - type: textarea
    id: aditional-context
    attributes:
      label: Additional context
    validations:
      required: false
